// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      D:\projects\GDE_Unity_5.6.5_Dev\Assets\GameDataEditor\SampleScenes\GDEReadDataScene\Resources\read_scene_data.json
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDESchemaKeys
    {
        public static string ReadScene = "ReadScene";
        public static string ReadSceneUnityTypes = "ReadSceneUnityTypes";
        public static string ReadSceneCustom = "ReadSceneCustom";
    }
}
