// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//
//      This file was generated from this data file:
//      C:/Project/HumanWeapon/Assets/GameDataEditor/Resources/gde_data.txt
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public partial class GDEItemKeys
    {
        public static string Hero_Hero_1 = "Hero_1";
        public static string Monster_Monster_1 = "Monster_1";
        public static string Magic_Magic_1 = "Magic_1";
        public static string Magic_Magic_2 = "Magic_2";
        public static string Item_Item_1 = "Item_1";
        public static string Item_Item_2 = "Item_2";
    }
}
